### ISSUE TITLE
Feeds that all entries those has same updateAt from RSSHub cause infinite request

### ISSUE THREAD

**Issue by enpitsuLin** [hyoban/follow-app#6]
See records, eg.`rsshub://hellogithub/volume`

https://github.com/user-attachments/assets/6dc3f8be-1460-46af-bb47-d82cab8d66de

Found that while the condition here causes an infinite loop, don't know why sub 1 min here, so open this issue

https://github.com/hyoban/follow-app/blob/992ae3f5cb81dcf627b321b9bf057bbcf9c499d0/api/entry.ts#L100

**Comment by hyoban** [comment]
Should be fixed in https://github.com/hyoban/follow-app/commit/992ae3f5cb81dcf627b321b9bf057bbcf9c499d0 ?
